### ISSUE TITLE
[DB설계] 기존 테이블 개선작업 > User 관련

### ISSUE THREAD

**Issue by NOTA2** [NOTA2/smusmu-reborn#4]

**Comment by beurmuz** [comment]
## User 관련 테이블
- USR: 사용자 정보
- MJR: 단과대학, 학부(과)/전공
## 참고사항
- major.ts파일을 푸시하긴 했으나 major와 college를 enum으로 관리할 지, 테이블로 관리할 지에 대해 의논해보아야 할 것 같습니다.
